import "./globals.css";
import { Inter } from "next/font/google";
import Header from "../components/Header"
import AnimatedCursor from "react-animated-cursor";
import Script from "next/script";

const inter = Inter({subsets:["latin"]});

export const metadata = {
    title: "Shiwa(a)",
    description : "Generated by Shiwa with love",
};

export default function RootLayout ({ children }) {

    return (
        <html lang="en">
            <body className={inter.className}>

                
          {children}
            </body>
        </html>
    );

}